### ISSUE TITLE
Is there a way to disable menu creation during conda install?

### ISSUE THREAD

**Issue by will133** [ContinuumIO/menuinst#37]
Is it possible to globally disable the menu creation during conda install?  In our experience, some packages can create non-functional links and we would like to avoid polluting user's menu.

**Comment by msarahan** [comment]
Yes. It is sufficient to remove the menuinst package.

Conda remove menuinst

**Comment by pgunn** [comment]
On windows, removing menuinst is not permitted:
![conda_no_remove_menuinst](https://user-images.githubusercontent.com/829791/41056929-ae0e4030-6993-11e8-8481-640c5e2e849b.png)

**Comment by whimian** [comment]
`conda remove menuinst` will remove `conda`.

**Comment by hmaarrfk** [comment]
Is there an other issue opened for this?

The recipe from the default channel requires menuinst for conda

https://github.com/AnacondaRecipes/conda-feedstock/blob/master/recipe/meta.yaml#L46

**Comment by jaimergp** [comment]
[`--no-shortcuts`](https://github.com/conda/conda/blob/fc81d4217f6c1804e983d1698f8b7cc5bc01874c/conda/cli/conda_argparse.py#L1672) should disable menu creation.
