### ISSUE TITLE
use of SHGetKnownFolderPath breaks compatibility with WinXP

### ISSUE THREAD

**Issue by greyltc** [ContinuumIO/menuinst#38]
The following commit seems to have broken compatibility with Windows XP:
14016caa3c90f4579fc7c9b74493a276ab5161f3 because `windll.shell32.SHGetKnownFolderPath` is not available on Windows XP.

**Comment by mingwandroid** [comment]
I do not think we support XP anymore, @csoja, @electronwill can you confirm that? Certainly Python 3.5 does not. You might be able to use Python 2.7 from on of the zip files in https://repo.continuum.io/archive/.winzip/ instead.

**Comment by greyltc** [comment]
I'm building installers for windows XP using https://github.com/conda/constructor
Python 3.4 works fine as do most of the latest versions of many popular packages (I just have to be careful to use the ones compiled with VC10).

Could this package be somehow modified to include detection for win XP and fail gracefully somehow (or better yet revert to the previous behavior that worked in XP) instead of going down in flames when SHGetKnownFolderPath can't be found?

**Comment by mingwandroid** [comment]
If we no longer officially support XP then we'll probably not spend time working this, however a PR would be considered.

**Comment by greyltc** [comment]
I'm not sure if the intention of https://github.com/ContinuumIO/menuinst/pull/27 was to drop support for XP (@msarahan was it?).

Looks like the notes say that the behavior for win>XP was meant to change. Maybe there's just a bug in that pull that accidentally breaks XP?

**Comment by ccordoba12** [comment]
@greyltc, Windows XP and Vista are not supported anymore by Continuum, sorry.

I'm closing this one as *Won't fix*

**Comment by electronwill** [comment]
I can confirm this; https://docs.continuum.io/anaconda/ lists Anaconda 2.2 as the final version to support XP. Sorry not to have better news for you @greyltc .

**Comment by silentquasar** [comment]
Disappointing. Some of us in the scientific community are stuck with legacy hardware that only runs on XP. It is a major headache for conda to break on XP.

**Comment by csoja** [comment]
@silentquasar you can keep your version of conda at the last version that did work for you on WindowsXP. https://conda.io/docs/config.html#update-conda-automatically-auto-update-conda

I wish we had more people and time...

**Comment by silentquasar** [comment]
@csoja Thank you for the response and info.
