### ISSUE TITLE
PythonW.exe not found during installation of "spyder" and other GUI items with conda

### ISSUE THREAD

**Issue by vx1920** [ContinuumIO/menuinst#64]
I have Win7-X86 and latest Anaconda3-X86, menuinst version 14.x.
 During installation of "spyder" and other GUI items I got message box "Windows can not find pythonw" along with suspicious log from "menuinst".
 I use Windows command line: "py -m conda install spyder". My own py.bat uses proper full path to python.exe followed by the above arguments from command line (Windows cmd.exe prompt).
 I did review sources in "Anaconda\Lib\site-packages\menuinst" and I found suspicious place in:
 
        Anaconda\Lib\site-packages\menuinst\ __init__.py, function install().

 Original fragment presented below:

            runAsAdmin(['pythonw', '-c',
                        "import menuinst; menuinst.install(%r, %r, %r)" % (
                            path, bool(remove), prefix)])
      

 Problem is that somebody is using full path everywhere in the generated menu item, while "pythonw" itself is caled without any path. I did modify call to "runAsAdmin" as below. I did change only the first item in [] argument from 'pythonw' to full path to pythonw (path is available in prefix variable):

      runAsAdmin(["%s\\pythonw.exe" % (prefix),
               '-c',
               "import menuinst; menuinst.install(%r, %r, %r)" % (
                  path, bool(remove), prefix)])

 After this modification I can see that pythonw.exe is started and request administrative elevation, as it supposed to be (maybe). It looks like that somebody have to fix something.

**Comment by vx1920** [comment]
I did update conda/menuinst in May-30-2018. I found that __init__.py was changed and mentioned fragment looks better ( pay attention to join() ):

                    retcode = runAsAdmin([join(sys.prefix, 'python'), '-c',
                                          "import menuinst; menuinst.install(%r, %r, %r, %r)" % (
                                              path, bool(remove), prefix, True)])

I don't know who did fix it and when, but looks good and this issue can be closed. Thank you any case.

**Comment by msarahan** [comment]
pythonw should absolutely be there, but if this fixes any problems that anyone had, I'm happy.  It's actually an unintentional change left over from trying to debug stuff.  I'm happy enough to leave it as is, though - it might show more quickly-disappearing black console windows is all.

**Comment by dlouhasha** [comment]
I Installed the 2020 07 version of windows 64-bit anaconda. The same problem still occurred. Wonder why
